### ISSUE TITLE
The readme quick start link is not pointing an active domain

### ISSUE THREAD

**Issue by number1hustler** [mondaycom/welcome-apps#118]
https://github.com/mondaycom/welcome-apps/tree/master/apps/quickstart-react
![Screenshot 2024-08-28 at 1 13 50 PM](https://github.com/user-attachments/assets/6bea3ed4-a26c-49ee-ac10-13b10b23f6ee)

To reproduce click the here link

**Comment by yuhgto** [comment]
Thank you! I'll pick it up soon
