### ISSUE TITLE
welcome apps - github-monday-code, does not work if follow instructions at all.

### ISSUE THREAD

**Issue by walektine** [mondaycom/welcome-apps#123]
Well, seems SETUP info is outdated, and some missing information how to setup Monday's app correctly.
What i feel, is lazy developer does manuals and doesn't care of quality of his work.

so, there are questions:
1. How are OAuth - Redirect URLs related to anything in app ?
2. How to setup - `Authorization URL` of Monday's app correctly? documentation is useless. i put `/auth` 
<img width="606" alt="Screenshot 2024-10-17 at 15 15 47" src="https://github.com/user-attachments/assets/3cb44c4a-cf93-4e73-a5e7-4b0fc905a300">

3. Try to integrate with github, but got error from github -
![Screenshot 2024-10-17 at 15 12 36](https://github.com/user-attachments/assets/b7663113-9d83-405f-b75f-dca91b58a3d7)
4. please check out your code for this project `github-monday-code` and make a new video how to setup it correctly.
 
thanks.

**Comment by yuhgto** [comment]
Hey @walektine – I'll take a look, I'm probably the Lazy Developer you're talking about 😉  We made some changes to monday code recently so possible that this broke. But will confirm

**Comment by yuhgto** [comment]
Hey @walektine – I went through the docs and found that everything works normally... I am preparing a PR to add a few more screenshots and clarify some of the instructions; but the code should work as-is and the instructions are not missing any steps.

To answer your questions: 

## How are OAuth URLs connected to the app? 

The app uses OAuth to authenticate with monday & Github. You need to supply the platforms with OAuth Redirect URLs so they know these URLs are legitimate.  

OAuth can be confusing as there are lots of steps and different parties involved. It is a standard protocol though, so there are a lot of resources available about it online. For example – https://auth0.com/intro-to-iam/what-is-oauth-2 

## Configuring OAuth URL

You need to set monday's redirect URL to point at the `/auth/monday/callback` route. Your screenshot has the wrong URL in it. 

The correct setup is in the [SETUP.md file here](https://github.com/mondaycom/welcome-apps/blob/master/apps/github-monday-code/SETUP.md#configure-oauth-in-monday)

## Github redirect URL error

If you set the wrong redirect URL in Github, you'll get an error. 

[This part of the SETUP.md file](https://github.com/mondaycom/welcome-apps/blob/master/apps/github-monday-code/SETUP.md#create-oauth-app) will show you the exact value to put for the redirect URL. 

## Moving forward

Setting up an OAuth app is a lot of steps, but it'll give you the most comprehensive understanding of our integrations infrastructure. 

If you'd like to start somewhere simpler (which I recommend for beginners), try starting with our integrations quickstart instead: 
[Instructions from our docs](https://developer.monday.com/apps/docs/quickstart-integration)
[Code is here](https://github.com/mondaycom/welcome-apps/tree/master/apps/quickstart-integrations)

**Comment by yuhgto** [comment]
Your GitHub Callback URL should be:
`(Your URL)/auth/github/callback `

Good catch: I noticed the written instructions are correct but the screenshot is wrong. Confusing. I’ll update it! 

Let me know if it works for you after making that change.
