### ISSUE TITLE
Library Version Upgrade

### ISSUE THREAD

**Issue by number1hustler** [mondaycom/welcome-apps#125]
Can the Vibe UI kit be upgraded to the next major version? Vibe is on 2.XX now, and it can be a bit confusing when the docs don't match the version that installs automatically. (Was trying a few things and it didn't work turned out the starter kits versions is pretty old)

https://github.com/mondaycom/welcome-apps/blob/master/apps/quickstart-react/package.json

**Comment by yuhgto** [comment]
@number1hustler Done in this PR: https://github.com/mondaycom/welcome-apps/pull/122

It updates vibe in all the quickstarts except for Word Cloud (which I have another PR open for, as it needs a bit more work than just upgrading to vibe). 

Go ahead and open another issue if you find any other weird behaviour
