### ISSUE TITLE
Setup.md update

### ISSUE THREAD

**Issue by number1hustler** [mondaycom/welcome-apps#127]
In this setup.md https://github.com/mondaycom/welcome-apps/blob/master/apps/github-monday-code/SETUP.md

Could the picture be updated to show a properly formatted github callback URL? Spent an embarrassingly long time troubleshooting a wrong callback URL because the pic and directions didn't match.
<img width="776" alt="Screenshot 2024-10-25 at 10 10 55 AM" src="https://github.com/user-attachments/assets/2010a18f-000d-4629-bada-c74a80d0f38a">
Hopefully the screenshot can end in: /auth/github/callback

**Comment by yuhgto** [comment]
Yes! Fixed in https://github.com/mondaycom/welcome-apps/pull/124
